services:
  web-dev: 
    build: 
      context: . 
      dockerfile: Dockerfile 
      target: dev 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development 
    volumes:
      - /app/node_modules 
    develop:
      watch:
        - action: sync 
          path: ./src
          target: /app/src
        
        - action: rebuild 
          path: ./public 
          target: /app/public
           
        - action: sync 
          path: ./prisma
          target: /app/prisma 

        - action: rebuild 
          path: package.json 

          ignore: 
            - node_modules/

          
