services:
  web-dev: 
    build: 
      context: . 
      dockerfile: Dockerfile 
      target: dev 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development 
    volumes:
      - .:/app 
      - /app/node_modules
