services:
  web-dev: 
    build: 
      context: . 
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
      - /app/node_modules 
    environment:
      - NODE_ENV=development 
    command: npm run dev 
  web-prod: 
    build: 
      context: . 
      target: prod
    ports:
      - "4000:3000"
    environment: 
      - NODE_ENV=production 
    command: npm start