'use client'; 
import type { Metadata } from "next";
import "./globals.css";

import { SessionProvider } from "next-auth/react";

// import components here 
import SideNav from '@/components/SideNav';



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-w-screen min-h-screen flex flex-col">
      <body
        
        className="flex-1 flex flex-row bg-[#CCCCCC]"
      >
        <SessionProvider>
          <SideNav />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
