
interface SessionCountFor8DaysProps { 
  session_date: number; 
  active_sessions: number; 
}

export const SessionCountFor8Days: SessionCountFor8DaysProps[] = [ 
  {session_date: 1, active_sessions: 0},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 0},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 0}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 0}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 0}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 400}, 
  {session_date: 7, active_sessions: 0}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 0}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 0}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550},
    {session_date: 1, active_sessions: 350},
  {session_date: 2, active_sessions: 250}, 
  {session_date: 3, active_sessions: 150}, 
  {session_date: 4, active_sessions: 125}, 
  {session_date: 5, active_sessions: 100}, 
  {session_date: 6, active_sessions: 0}, 
  {session_date: 7, active_sessions: 600}, 
  {session_date: 8, active_sessions: 550}
]